###
### Creating various local and remote directories
###

# On Ansible control node
# Creating LOCAL dir on Ansible control node to collect ALL control json outputs
  - name: Creating LOCAL dir on Ansible control node to collect ALL control json outputs "{{ tbl_check_json_output_dir_local }}"
    local_action:
      module: file
      path: "{{ tbl_check_json_output_dir_local }}"
      owner: root
      group: root
      state: directory
    when:
      - inventory_hostname in groups['ansible_control_node'][0]

# on TARGET VM
# Create remote dir to collect control json outputs
  - name: Creating remote dir to collect control json outputs "{{ tbl_check_json_output_dir_remote }}"
    file:
      path: "{{ tbl_check_json_output_dir_remote }}"
      owner: root
      group: root
      state: directory
    when:
      - inventory_hostname in groups['tbl_checklist']


###
### Copy over Actual Inspec Control RB files to VMs
###

  - name: Creating remote Inspec base dir "{{ tbl_check_remote_inspec_base_dir }}"
    file:
      path: "{{ tbl_check_remote_inspec_base_dir }}"
      owner: root
      group: root
      state: directory
    when:
      - inventory_hostname in groups['tbl_checklist']

  - name: Creating remote Inspec dir for holding the control RB files "{{ tbl_check_remote_inspec_control_dir }}"
    file:
      path: "{{ tbl_check_remote_inspec_control_dir }}"
      owner: root
      group: root
      state: directory
    when:
      - inventory_hostname in groups['tbl_checklist']

  - name: Template Inspec profile to remote Inspec base dir "{{ tbl_check_remote_inspec_base_dir }}"
    template:
      src: templates/TBL_Linux/inspec.yml.j2
      dest: "{{ tbl_check_remote_inspec_base_dir }}/inspec.yml"
      owner: root
      group: root

  - name: Template Inspec script to be run at remote server "{{ tbl_check_remote_inspec_base_dir }}"
    template:
      src: templates/TBL_Linux/make_elastic_localfile.sh.j2
      dest: "{{ tbl_check_remote_inspec_base_dir }}/make_elastic_localfile.sh"
      owner: root
      group: root
      mode: 0755

  - name: Copy over all InSpec RB files
    copy:
      src: "{{ item }}"
      dest: "{{ tbl_check_remote_inspec_control_dir }}"
      owner: root
      group: root
    with_fileglob:
      - "{{ tbl_check_local_inspec_control_dir }}/*.rb"

###
### RUN Inspec Control
###

  - name: RUN InSpec tests
    command: "{{ tbl_check_remote_inspec_base_dir }}/make_elastic_localfile.sh"
